### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Ippephyx** [Oliv4945/Photokey#3]
Bonjour @Oliv4945 
Je suis sincèrement navré de venir polluer votre Git... Mais je n'ai pas trouver d'autres moyens de vous contacter; nous avons rapidement échanger sur le GIT de Jarvis...

Je me suis rendu compte que vous être sur Grenoble... Moi-même je suis dans le voironnais et viens de lancer une micro-entreprise dans la domotique ( www.synapteec.fr ). J'aurai juste voulu voir si nous pouvions échanger un peu.

Bien cordialement,

GR.

**Comment by Oliv4945** [comment]
Bonjour,

J'ai répondu par email à votre email de contact synapteec.

Oliv'

**Comment by Oliv4945** [comment]
Bonjour,

Il semblerait que vote email soit mal configuré, j'ai eu le message de retour:

> The mail system <contact@synapteec.fr>: host mx00.1and1.fr[212.227.15.41] said: 550-Requested
>     action not taken: mailbox unavailable 550 invalid DNS MX or A/AAAA resource
>     record (in reply to MAIL FROM command)

Mon message était:

>Il est bien entendu possible d'échanger par email, téléphone ou même demain soir si vous êtes disponible au Laboratoire Ouvert Grenoblois. C'est un association où il y a d'autres aficionados de la domotique :)

Adresse du LOG: https://www.logre.eu/

Oliv'
